from __future__ import annotations
from typing import Protocol

class ContextStore(Protocol):
    def reset(self) -> None: ...
    def upsert(self, name: str, description: str, aliases: list[str]) -> None: ...
    def save(self) -> None: ...
    def relevant_snippet(self, page_text: str) -> str: ...
    def export_snapshot(self, dest_path: str) -> None: ...
